<a href="https://colab.research.google.com/github/vartikaabc/vartikaabc/blob/main/campus_recruitment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q kaggle

In [ ]:
from google.colab import files
files.upload()

Saving kaggle (1).json to kaggle (1) (1).json


{'kaggle (1).json': b'{"username":"vartikaabc","key":"8090182623e13eb29066227c3781258f"}'}

In [ ]:
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/

mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [ ]:
!kaggle datasets list

ref                                                         title                                              size  lastUpdated          downloadCount  
----------------------------------------------------------  ------------------------------------------------  -----  -------------------  -------------  
gpreda/reddit-vaccine-myths                                 Reddit Vaccine Myths                              237KB  2021-10-29 12:28:54          14692  
crowww/a-large-scale-fish-dataset                           A Large Scale Fish Dataset                          3GB  2021-04-28 17:03:01           8785  
imsparsh/musicnet-dataset                                   MusicNet Dataset                                   22GB  2021-02-18 14:12:19           3933  
dhruvildave/wikibooks-dataset                               Wikibooks Dataset                                   2GB  2021-10-22 10:48:21           3278  
promptcloud/careerbuilder-job-listing-2020                  Careerbuilder Jo

In [ ]:
!kaggle datasets download -d benroshan/factors-affecting-campus-placement

factors-affecting-campus-placement.zip: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
!chmod 600 /root/.kaggle/kaggle.json

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/factors-affecting-campus-placement.zip")

In [ ]:
df.head()

sl_no gender  ssc_p    ssc_b  ...  specialisation  mba_p      status    salary
0      1      M  67.00   Others  ...          Mkt&HR  58.80      Placed  270000.0
1      2      M  79.33  Central  ...         Mkt&Fin  66.28      Placed  200000.0
2      3      M  65.00  Central  ...         Mkt&Fin  57.80      Placed  250000.0
3      4      M  56.00  Central  ...          Mkt&HR  59.43  Not Placed       NaN
4      5      M  85.80  Central  ...         Mkt&Fin  55.50      Placed  425000.0

[5 rows x 15 columns]

In [ ]:
df = df.drop('sl_no', axis=1)
df = df.drop('salary', axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   gender          215 non-null    int8   
 1   ssc_p           215 non-null    float64
 2   ssc_b           215 non-null    int8   
 3   hsc_p           215 non-null    float64
 4   hsc_b           215 non-null    int8   
 5   hsc_s           215 non-null    int8   
 6   degree_p        215 non-null    float64
 7   degree_t        215 non-null    int8   
 8   workex          215 non-null    int8   
 9   etest_p         215 non-null    float64
 10  specialisation  215 non-null    int8   
 11  mba_p           215 non-null    float64
 12  status          215 non-null    int8   
dtypes: float64(5), int8(8)
memory usage: 10.2 KB


In [ ]:
df["gender"] = df["gender"].cat.codes
df["ssc_b"] = df ["ssc_b"].cat.codes
df["hsc_b"] = df["hsc_b"].cat.codes
df["degree_t"] = df["degree_t"].cat.codes
df["workex"] = df["workex"].cat.codes
df["specialisation"] = df["specialisation"].cat.codes
df["status"] = df["status"].cat.codes
df["hsc_s"] = df["hsc_s"].cat.codes

In [ ]:
df

gender  ssc_p  ssc_b  hsc_p  ...  etest_p  specialisation  mba_p  status
0         1  67.00      1  91.00  ...     55.0               1  58.80       1
1         1  79.33      0  78.33  ...     86.5               0  66.28       1
2         1  65.00      0  68.00  ...     75.0               0  57.80       1
3         1  56.00      0  52.00  ...     66.0               1  59.43       0
4         1  85.80      0  73.60  ...     96.8               0  55.50       1
..      ...    ...    ...    ...  ...      ...             ...    ...     ...
210       1  80.60      1  82.00  ...     91.0               0  74.49       1
211       1  58.00      1  60.00  ...     74.0               0  53.62       1
212       1  67.00      1  67.00  ...     59.0               0  69.72       1
213       0  74.00      1  66.00  ...     70.0               1  60.23       1
214       1  62.00      0  58.00  ...     89.0               1  60.22       0

[215 rows x 13 columns]

In [ ]:
X = df.iloc[:, :-1].values
Y = df.iloc[:, -1].values

In [ ]:
Y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int8)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,
                                                    test_size=0.2)

In [ ]:
df.head()

gender  ssc_p  ssc_b  hsc_p  ...  etest_p  specialisation  mba_p  status
0       1  67.00      1  91.00  ...     55.0               1  58.80       1
1       1  79.33      0  78.33  ...     86.5               0  66.28       1
2       1  65.00      0  68.00  ...     75.0               0  57.80       1
3       1  56.00      0  52.00  ...     66.0               1  59.43       0
4       1  85.80      0  73.60  ...     96.8               0  55.50       1

[5 rows x 13 columns]

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
clf = LogisticRegression(random_state=0, solver='lbfgs',
                         max_iter=1000).fit(X_train,
                                            Y_train)

In [ ]:
clf.score(X_test, Y_test)

0.8372093023255814

In [ ]:
clf.predict([[0, 87, 0, 95, 0, 2, 78, 2, 0, 0, 1, 0]])

array([1], dtype=int8)

In [ ]:
Y_pred = clf.predict(X_test)

In [ ]:
Y_pred

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0],
      dtype=int8)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
print(confusion_matrix(Y_test, Y_pred))

[[11  5]
 [ 2 25]]


In [ ]:
print(accuracy_score(Y_test, Y_pred))

0.8372093023255814
